name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_KEY }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: easc01/disaster-media-api:latest

      - name: Verify Pushed Image
        run: docker pull easc01/disaster-media-api:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            sudo docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_ACCESS_KEY }}
            sudo docker pull easc01/disaster-media-api:latest
            
            sudo docker stop disaster-media-container || true
            sudo docker rm disaster-media-container || true
            
            sudo docker run -d \
              --name disaster-media-container \
              --restart=unless-stopped \
              -p ${{ vars.SERVER_PORT }}:${{ vars.SERVER_PORT }} \
              -e SERVER_PORT=${{ vars.SERVER_PORT }} \
              -e DATABASE_URL=${{ secrets.DATABASE_URL }} \
              -e DATABASE_USERNAME=${{ secrets.DATABASE_USERNAME }} \
              -e DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }} \
              -e YOUTUBE_API_KEY=${{ secrets.YOUTUBE_API_KEY }} \
              easc01/disaster-media-api:latest